# Generated by Django 3.2.4 on 2021-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_num', models.CharField(max_length=16, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_point', models.CharField(max_length=200, verbose_name='Точка A')),
                ('b_point', models.CharField(max_length=200, verbose_name='Точка B')),
            ],
        ),
    ]
