# Generated by Django 3.2.4 on 2021-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_client_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='route',
        ),
        migrations.AddField(
            model_name='client',
            name='route',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Route', verbose_name='Маршрут'),
        ),
    ]
