# Generated by Django 3.2.4 on 2021-11-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='location_photo',
        ),
    ]
