# Generated by Django 3.2.4 on 2021-11-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20211108_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='Имя водителя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_num',
            field=models.CharField(default=0, max_length=16, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.client'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bot.route'),
        ),
    ]
