# Generated by Django 3.2.4 on 2021-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20211108_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=100, verbose_name='Откуда')),
                ('_to', models.CharField(max_length=100, verbose_name='Куда')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Клиент', 'client'), ('Водитель', 'driver')], max_length=100, verbose_name='Тип пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_num', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('car_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер машины')),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='client',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='route',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
