# Generated by Django 3.2.4 on 2021-11-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(choices=[], default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='bot.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(choices=[('Мухаммадазиз', 'Мухаммадазиз'), ('Рустам', 'Рустам')], default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='bot.user'),
            preserve_default=False,
        ),
    ]
