# Generated by Django 3.2.4 on 2021-11-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20211108_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(default=0, max_length=100, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(default=0, max_length=100, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='bot.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver', to='bot.user'),
        ),
    ]
