# Generated by Django 3.2.4 on 2021-11-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20211108_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', related_query_name='client', to='bot.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', related_query_name='driver', to='bot.user'),
        ),
    ]
