# Generated by Django 3.2.4 on 2021-11-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_order_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=0, verbose_name='Окончен'),
            preserve_default=False,
        ),
    ]
