# Generated by Django 3.2.9 on 2021-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20211110_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo',
            field=models.CharField(default=0, max_length=100, verbose_name='Наименование груза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default=0, max_length=100, verbose_name='Дата погрузки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.CharField(default=0, max_length=100, verbose_name='Вес груза'),
            preserve_default=False,
        ),
    ]
