# Generated by Django 3.2.9 on 2021-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20211118_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.BooleanField(blank=True, null=True, verbose_name='Окончен'),
        ),
    ]
