# Generated by Django 3.2.9 on 2021-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_order_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_num',
            field=models.CharField(default=0, max_length=16, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
