# Generated by Django 3.2.9 on 2021-11-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_order_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name='Дата погрузки'),
        ),
    ]
