# Generated by Django 3.2.9 on 2021-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Окончен'),
        ),
    ]
