# Generated by Django 3.2.9 on 2021-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_alter_order_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('driver', 'Водитель'), ('admin', 'Админ')], max_length=100, verbose_name='Тип пользователя'),
        ),
    ]
